FROM python:3.11-bullseye

RUN mkdir -p /home/app

COPY . home/app

WORKDIR /home/app

EXPOSE 80


RUN pip install --no-cache-dir -r requirements.txt
RUN pip install zaptools

CMD uvicorn main:app --host 0.0.0.0 --port $PORT