FROM python:3.12-slim

RUN mkdir -p /home/app

COPY . home/app

WORKDIR /home/app

EXPOSE 80

RUN pip install --no-cache-dir -r requirements.txt

CMD uvicorn main:app --host 0.0.0.0 --port $PORT
# Railway must to setup manually
